#!/bin/bash

raw=(
192.168.109.1
192.168.109.2
192.168.109.3
192.168.109.4
192.168.109.5
192.168.109.7
192.168.109.8
10.226.0.1
10.226.0.2
10.226.1.3
192.168.109.6
10.226.0.4
10.22.0.4
10.22.0.5
)

# Create associative array of hosts and initialise
declare -A hosts

for h in ${raw[*]}
do
	hosts[$h]=unknown
done

# Declare known subnets
declare -A masks
masks=(
[192.168.109]=foonet
[10.226.0]=barnet
)

# Header
cat <<!
graph
{
	node [style=filled fillcolor=cyan]

!

# Examine hosts
for ip in ${!hosts[*]}
do
	# Test each mask
	for mask in ${!masks[*]}
	do
		# Stash mask name if the ip matches and stop search
		if [[ $ip =~ $mask ]]
		then
			hosts[$ip]=${masks[$mask]}
			break
		fi
	done
done

# Dump connections
for ip in ${!hosts[@]}
do
	echo -e "\t\"$ip\" -- \"${hosts[$ip]}\""
done

# Footer
cat <<!

	// $(date)
}
!
