#!/bin/bash

# Go back to IPs only

for w in $@
do
	tpath=$(tracepath -m 5 $w)

	# Extract betwixt the colons
	while [[ $tpath =~ [[:digit:]\?\/]+:[^:]+ ]]
	do
		line=$BASH_REMATCH
		tpath=${tpath/"$line"//}

		# Get the host
		[[ $line =~ [[:alpha:][:digit:]\.]+ ]] && hosts+=($BASH_REMATCH)
	done

done

# Format for dot
for (( i = 0; i < ${#hosts[@]} - 1; ++i ))
do
echo \"${hosts[$i]}\" -- \"${hosts[$i + 1]}\"\;
done
